### ISSUE TITLE
Popup telling the user that points will be deducted is shown to users who aren't logged in

### ISSUE THREAD

**Issue by bionfinc** [bionfinc/pomodoro#28]
Users that aren't logged in don't have points, so they shouldn't be shown this message.

Reproduction steps:
1. Start pomodoro
2. Click short/long break button
3. See popup message

**Comment by adorgan** [comment]
I actually did this purposely to show users without accounts that points are a part of the task/break process. I think a pop-up is good for unregistered users to alert them that they are interrupting the task. I can make a change to alter the pop-up text depending on account status, or just get rid of the pop-up altogether for unregistered users. Either option should be pretty easy to implement.

**Comment by ckuchman** [comment]
I think that makes sense to a degree, but I think the wording should be changed for the non-user to better imply that it knows you don't have points to lose. The way it stands, it is easy to think that it is a error and not intentional.

**Comment by bionfinc** [comment]
I agree. I think it's good to have a popup notifying the user that they are interrupting their task. If the wording can be separated for logged out users then I think that would be our best option
