### ISSUE TITLE
Replace alerts with Bootstrap modals

### ISSUE THREAD

**Issue by bionfinc** [bionfinc/pomodoro#47]
Javascript alerts that we currently use on the timer page to let the user know if they are ending a session early or get points can be a bit spammy. Most (if not all) browsers will suggest to the user to ignore them if more than 1 pops up.

We should replace these alerts with Bootstrap modal windows: 
https://getbootstrap.com/docs/4.0/components/modal/

Modals tend to look nicer, and also users can't just press an ignore checkbox and never see one again.

**Comment by adorgan** [comment]
I agree! I will add this into my tasks for this sprint. If anyone else wants to try this out, feel free to assign yourself to the task.

**Comment by ckuchman** [comment]
Resolved with pull request #59
