### ISSUE TITLE
On chrome, keeps asking me to translate page from Norwegian. 

### ISSUE THREAD

**Issue by adorgan** [bionfinc/pomodoro#57]
Not sure if anyone else is getting this, but when I login to the site or refresh the index page while using chrome, the browser asks me if I want to translate the page from Norwegian. I'm not really sure why but it is thinking that the word 'pause' on the pause button is Norwegian and wants to translate it to the English word 'break'.

**Comment by bionfinc** [comment]
I think this is because we don't have the html "lang" attribute setup on the base template. Apparently if the page doesn't have very many words then Google has issues figuring out what language the page is in if there isn't a lang attribute on the page.

**Comment by adorgan** [comment]
Yep, fixed by adding the lang attribute. Thanks!
