### ISSUE TITLE
logout URL

### ISSUE THREAD

**Issue by adorgan** [bionfinc/pomodoro#72]
When you logout, the url you are directed to is https://pomodoro-posse.herokuapp.com/logout/ and it stays like that unless you click a new link. I thought it would be better if when you logged out it would direct you to the base URL without the '/logout' afterwards. It's an easy fix, just add LOGOUT_REDIRECT_URL to the settings. I was curious if people thought it would be better to redirect to the index page or maybe the login page? I noticed some web sites handle this differently so just curious what others think.

**Comment by ja-osu** [comment]
I think for our project it would make sense to link back to the index page since a user doesn't need to be logged into the site to use it.
