### ISSUE TITLE
session description shows 'usersessions.UserSession.objects'

### ISSUE THREAD

**Issue by adorgan** [bionfinc/pomodoro#82]
Upon first logging on site, the description is empty as intended. If you click on the profile page and then return to the timer page, the description shows this: 
![sessiondescription](https://user-images.githubusercontent.com/42968619/89592062-5cbaa180-d811-11ea-8548-70add5d1047b.png)

**Comment by ckuchman** [comment]
Looking like it was my commit, I see the typo and can get it fixed.
